

/* ------------------------- LIBRERÍAS ------------------------------- */

OPTIONS SYMBOLGEN;
LIBNAME ARCHCOMP BASE "/sasdatosued/Archivos_compartidos" ;
%LET LIB=ARCHCOMP.;


/* Millones de pesos */
%LET MDP=1000000;
%PUT &MDP;

/* Cifra mensual */
PROC SQL;
CREATE TABLE RAMO_AC01_0826 AS 
SELECT DISTINCT A.ID_RAMO,
A.ID_PP,
PP_DESC,
CASE WHEN B.ID_PP=A.ID_PP THEN "1" ELSE "0" END AS PRIORITARIO,
SUM(ORI_ANUAL)/&MDP AS ORI_ANUAL,
SUM(ORI_PERIODO)/&MDP AS ORI_PERIODO,
SUM(MOD_ANUAL)/&MDP AS MOD_ANUAL,
SUM(MOD_PERIODO)/&MDP AS MOD_PERIODO,
SUM(PAG_PERIODO)/&MDP AS PAG_PERIODO
FROM &LIB.AC01_0826 A, WORK.PROGRAMAS_PRIORITARIOS_PPEF B
WHERE A.ID_RAMO="11"
GROUP BY A.ID_RAMO, A.ID_PP;
QUIT;


